name = "Baldeweg Businesscard"
license = "MIT"
licenselink = "https://github.com/abaldeweg/businesscard/blob/master/LICENSE"
description = ""
homepage = "https://github.com/abaldeweg/businesscard"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "André Baldeweg"
  homepage = "https://github.com/abaldeweg/businesscard"

[original]
  name = "André Baldeweg"
  homepage = "https://github.com/abaldeweg/components"
  repo = "https://github.com/abaldeweg/components.git"
